name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Tex Live and XeLaTex
      uses: dante-ev/latex-action@2021-A
      with:
        root_file: resume-cn.tex
        compiler: xelatex
        args: -synctex=1 -interaction=nonstopmode -file-line-error -pdf
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: resume-cn.pdf
        path: resume-cn.pdf