name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Tex Live
      uses: paolobrasolin/setup-texlive-action@v1
    - name: Build PDF
      run: make
